<?php
/**
 * Created by PhpStorm.
 * User: baidu
 * Date: 15/9/12
 * Time: 下午5:29
 */
/**
 * 友情链接
 */
function friendLink()
{
    wp_nav_menu(array(
        'theme_location'=>'friend-link',
        'container'=>'div',
        'container_class'=>'widget widget_categories',
        'fallback_cb' => 'wp_page_menu',
        'items_wrap'=>'<h2 class="widget-title">友情链接</h2><ul>%3$s</ul>',
        'echo'=>true,
        'walker'=>new Custom_Walker_Nav_Menu(),
    ));
}
/**
 * 自定义Walker用于实现跳转
 * Class Custom_Walker_Nav_Menu
 */
class Custom_Walker_Nav_Menu extends Walker_Nav_Menu{
    public function start_el(&$output, $item, $depth = 0, $args = array(), $id = 0)
    {
        $item->target = '_blank';
        parent::start_el($output, $item, $depth, $args, $id); // TODO: Change the autogenerated stub
    }

}
?>